name: Multipublish
description: Automatically publish JavaScript modules to a registry (like the npm registry). The code base is scanned for JavaScript modules, each of which is published to the specified registry (default is npm). Respects .npmrc files if present in the module's root directory.
author: Author.io
branding:
  icon: box
  color: red
inputs:
  scan:
    description: Optional. Specify which directories (relative to the root) should be scanned for modules. Comma separated.
    required: false
    default: ./
  version:
    description: Only publish modules matching this version.
    required: false
runs:
  using: "node12"
  main: "lib/main.js"
